---
# For config


# [tcp default]

#SendBufferMemory: 2M
#ReceiveBufferMemory: 2M

# Increasing the sizes of these 2 buffers beyond the default values
# helps prevent bottlenecks due to slow disk I/O.


# [ndb_mgmd default]

management_data_dir: /var/lib/mysql-cluster
management_config_dir: /var/lib/mysql-cluster


# Data Nodes
#[ndbd default]
DataDir: /var/lib/mysql-cluster
NumberOfReplicas: 2

# Number of Replicas
# NumberOfNodeGroup = NumberOfDataNodes/NumberOfReplicas
# Using two fragment replicas is recommended to guarantee availability of data;
# using only one fragment replica does not provide any redundancy, which means
# that the failure of a single data node causes the entire cluster to shut down. 
# It is also possible (but not required) in NDB 8.0 to use more than two
# fragment replicas, although two fragment replicas are sufficient to provide
# high availability. 

#LockPagesInMainMemory: 1

# On Linux and Solaris systems, setting this parameter locks data node
# processes into memory. Doing so prevents them from swapping to disk,
# which can severely degrade cluster performance.

#DataMemory: 3456M

# The value provided for DataMemory assumes 4 GB RAM
# per data node. However, for best results, you should first calculate
# the memory that would be used based on the data you actually plan to
# store (you may find the ndb_size.pl utility helpful in estimating
# this), then allow an extra 20% over the calculated values. Naturally,
# you should ensure that each data node host has at least as much
# physical memory as the sum of these two values.

#ODirect: 1

# Enabling this parameter causes NDBCLUSTER to try using O_DIRECT
# writes for local checkpoints and redo logs; this can reduce load on
# CPUs. We recommend doing so when using NDB Cluster on systems running
# Linux kernel 2.6 or later.

#NoOfFragmentLogFiles: 300

#MaxNoOfConcurrentOperations: 100000

#SchedulerSpinTimer: 400
#SchedulerExecutionTimer: 100
#RealTimeScheduler: 1

# Setting these parameters allows you to take advantage of real-time scheduling
# of NDB threads to achieve increased throughput when using ndbd. They
# are not needed when using ndbmtd; in particular, you should not set
# RealTimeScheduler for ndbmtd data nodes.

#TimeBetweenGlobalCheckpoints: 1000
#TimeBetweenEpochs: 200
#RedoBuffer: 32M

# CompressedLCP=1
# CompressedBackup=1
# Enabling CompressedLCP and CompressedBackup causes, respectively, local
# checkpoint files and backup files to be compressed, which can result in a space
# savings of up to 50% over noncompressed LCPs and backups.

# MaxNoOfLocalScans=64
#MaxNoOfTables: 1024
#MaxNoOfOrderedIndexes: 256
